# .github/workflows/compress-images.yml
name: Compress Images

on:
  pull_request:
    paths:
      - 'docs/assets/images/**'

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: calibreapp/image-actions@main
        with:
          compressOnly: false
          jpegQuality: 80
          pngQuality: 80
          webpQuality: 80
          avifQuality: 75
          ignorePaths: node_modules/**
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🖼️ Bilder komprimiert"
          file_pattern: docs/assets/images/**